// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are configured only for web. '
      'Run FlutterFire CLI again to configure other platforms.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasIqM_vDvTsmBUHiJ6Km27AMOtVXq6dM',
    appId: '1:438033937768:web:a280e14b7d86817d3f92dd',
    messagingSenderId: '438033937768',
    projectId: 'srisparksapplication',
    authDomain: 'srisparksapplication.firebaseapp.com',
    storageBucket: 'srisparksapplication.firebasestorage.app',
    measurementId: 'G-VTJLQV94C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1mUjNAYoyq7tk2TcXydpLilnGX4Dhb8',
    appId: '1:438033937768:android:c3781c88517981dc3f92dd',
    messagingSenderId: '438033937768',
    projectId: 'srisparksapplication',
    storageBucket: 'srisparksapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91G9VSuIEMZU5Ji5vOEIEM8aLoVHbB2A',
    appId: '1:438033937768:ios:6f911daec52ba2b93f92dd',
    messagingSenderId: '438033937768',
    projectId: 'srisparksapplication',
    storageBucket: 'srisparksapplication.firebasestorage.app',
    iosBundleId: 'com.example.srisparksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91G9VSuIEMZU5Ji5vOEIEM8aLoVHbB2A',
    appId: '1:438033937768:ios:6f911daec52ba2b93f92dd',
    messagingSenderId: '438033937768',
    projectId: 'srisparksapplication',
    storageBucket: 'srisparksapplication.firebasestorage.app',
    iosBundleId: 'com.example.srisparksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDasIqM_vDvTsmBUHiJ6Km27AMOtVXq6dM',
    appId: '1:438033937768:web:7ae8a86141feac223f92dd',
    messagingSenderId: '438033937768',
    projectId: 'srisparksapplication',
    authDomain: 'srisparksapplication.firebaseapp.com',
    storageBucket: 'srisparksapplication.firebasestorage.app',
    measurementId: 'G-HRX9GJJQKE',
  );
}
